// Code generated by go2go; DO NOT EDIT.


//line abs.go2:1
package mathz

//line abs.go2:1
import (
//line abs.go2:1
 "github.com/go2pkg/constraints"
//line abs.go2:1
 "math"
//line abs.go2:1
)

//line abs.go2:1
type Importable୦ int
//line abs.go2:1
type _ constraints.Importable୦

//line abs.go2:1
var _ = math.Abs
