// Code generated by go2go; DO NOT EDIT.


//line max.go2:1
package mathz

//line max.go2:1
import (
//line max.go2:1
 "github.com/go2pkg/constraints"
//line max.go2:1
 "math"
//line max.go2:1
)

//line max.go2:1
type _ constraints.Importable୦

//line max.go2:1
var _ = math.Abs
